  <div class="grid_12 header">
  <div class="grid_3 alpha topleft">
    <p><a href="index.html">Nicholas Eriksson</a></p>
  </div>

  <div class="grid_7">
    <nav role="navigation"> 
    <ul class="group">
    <li class="active"><a href="index.html"><strong>Home</strong></a></li>
    <li><a href="papers.html" title=""><strong>Papers</strong></a></li>
    <li><a href="http://nickeriksson.blogspot.com" title=""><strong>Blog </strong></a></li>
    <li><a href="eriksson-cv.html" title=""><strong>Vitae</strong></a></li>
    </ul>
    </nav>
  </div>

  <div class="grid_2 omega">
    <a href="img/IMG_9793-1.jpg"><img src="img/IMG_9793-1.jpg" 
        alt="me" align="right" width="130" height="130"/></a>
    </div>
  </div>

  <div class="clear"></div>

